# -*- coding: utf-8 -*-
"""
module:: rsas
moduleauthor:: Ciaran J. Harman
"""

from __future__ import division
import numpy as np
from warnings import warn
import time
dtype = np.float32

# for debugging
DEBUG = True
VERBOSE = True

def _debug(statement):
    """Prints debugging messages if DEBUG == True"""
    if DEBUG:
        print(statement)


def _verbose(statement):
    """Prints debugging messages if VERBOSE == True"""
    if VERBOSE:
        print(statement)

def solve(dis_rate, J, Q, rSAS_fun, mode='RK4', ST_init=None, dt=1, n_substeps=1,
          full_outputs=True, CS_init=None, C_J=None, alpha=None, k1=None,
          C_eq=None, C_old=None, verbose=False, debug=False):
    """Solve the rSAS model for given fluxes

    Args:
        J : n x 1 float64 ndarray
            Timestep-averaged inflow timeseries for n timesteps
        Q : n x q float64 ndarray or list of length n 1D float64 ndarray
            Timestep-averaged outflow timeseries for n timesteps and q outflow
            fluxes.  Must have same units and length as J.  For multiple
            outflows, each column represents one outflow
        rSAS_fun : rSASFunctionClass or list of rSASFunctionClass generated by
            rsas.create_function.  The number of rSASFunctionClass in this list
            must equal the number of columns in Q if Q is an ndarray, or
            elements in Q if it is a list.

    Kwargs:
        ST_init : m+1 x 1 float64 ndarray
            Initial condition for the age-ranked storage.  The length of
            ST_init determines the maximum age calculated.  The first entry
            must be 0 (corresponding to zero age).  To calculate transit-time
            distributions up to m timesteps in age, ST_init should have length
            m + 1.  The default initial condition is ST_init=np.zeros(len(J)+1).
        dt : float (default 1)
            Timestep, assuming same units as J
        n_substeps : int (default 1)
            If n_substeps > 1, the timesteps are subdivided for a more accurate
            solution.
        full_outputs : bool (default True)
            Option to return the full state variables array ST, the cumulative
            transit-time distributions PQ, and other variables
        verbose : bool (default False)
            Print information about the progression of the model
        debug : bool (default False)
            Print information every sub-step
        C_J, CS_init, C_old, alpha, k1, C_eq
            See original documentation for details.

    Returns:
        Dictionary of simulation results (see original documentation).
    """
    # Input checking and preparation
    global VERBOSE
    global DEBUG
    VERBOSE = verbose
    DEBUG = debug

    if not isinstance(J, np.ndarray):
        J = np.array(J)
    if J.ndim != 1:
        raise TypeError('J must be a 1-D array')
    J = J.astype(np.float32)

    if not isinstance(Q, np.ndarray):
        Q = np.array(Q).T
    Q = Q.astype(np.float32)

    if (Q.ndim > 2) or (Q.shape[0] != len(J)):
        raise TypeError(
            "Q must be a 1- or 2-D numpy array with a column for each "
            "outflow, or a list of 1-D numpy arrays (e.g. [Q1, Q2]); each "
            "must be the same size as J"
        )
    elif Q.ndim == 1:
        Q = np.c_[Q]

    if ST_init is not None:
        if not isinstance(ST_init, np.ndarray):
            ST_init = np.array(ST_init)
        if ST_init.ndim != 1:
            raise TypeError('ST_init must be a 1-D array')
        if ST_init[0] != 0:
            raise TypeError('ST_init[0] must be 0')
    else:
        ST_init = np.zeros(len(J) + 1)

    if not isinstance(rSAS_fun, list):
        rSAS_fun = [rSAS_fun]
    if Q.shape[1] != len(rSAS_fun):
        raise TypeError(
            "Each rSAS function must have a corresponding outflow in Q. "
            "Numbers don’t match"
        )
    for fun in rSAS_fun:
        fun_methods = [m for m in dir(fun) if callable(getattr(fun, m))]
        if not ('cdf_all' in fun_methods and 'cdf_i' in fun_methods):
            raise TypeError(
                "Each rSAS function must have methods rSAS_fun.cdf_all and "
                "rSAS_fun.cdf_i"
            )

    if not isinstance(full_outputs, bool):
        raise TypeError('full_outputs must be a boolean (True/False)')

    # ----- Optional solute inputs ------------------------------------------------
    if C_J is not None:
        if not isinstance(C_J, np.ndarray):
            C_J = np.array(C_J, dtype=dtype)
        if (C_J.ndim > 2) or (C_J.shape[0] != len(J)):
            raise TypeError(
                'C_J must be a 1- or 2-D array whose first dimension equals len(J)'
            )
        elif C_J.ndim == 1:
            C_J = np.c_[C_J]
        C_J = C_J.astype(np.float32)

        # ----- alpha -------------------------------------------------------------
        if alpha is not None:
            if not isinstance(alpha, np.ndarray):
                alpha = np.array(alpha, dtype=dtype)
            if alpha.ndim == 2:
                alpha = np.tile(alpha, (len(J), 1, 1))
            if (alpha.shape[2] != C_J.shape[1]) or (alpha.shape[1] != Q.shape[1]):
                raise TypeError("alpha array dimensions don't match other inputs")
            alpha = alpha.astype(dtype)
        else:
            alpha = np.ones((len(J), Q.shape[1], C_J.shape[1]))

        # ----- k1 ----------------------------------------------------------------
        if k1 is not None:
            if not isinstance(k1, np.ndarray):
                k1 = np.array(k1, dtype=dtype)
            if k1.ndim == 1:
                k1 = np.tile(k1, (len(J), 1))
            if (k1.shape[1] != C_J.shape[1]) or (k1.shape[0] != J.shape[0]):
                raise TypeError("k1 array dimensions don't match other inputs")
            k1 = k1.astype(dtype)
        else:
            k1 = np.zeros((len(J), C_J.shape[1]))

        # ----- C_eq --------------------------------------------------------------
        if C_eq is not None:
            if not isinstance(C_eq, np.ndarray):
                C_eq = np.array(C_eq, dtype=dtype)
            if C_eq.ndim == 1:
                C_eq = np.tile(C_eq, (len(J), 1))
            if (C_eq.shape[1] != C_J.shape[1]) or (C_eq.shape[0] != J.shape[0]):
                raise TypeError("C_eq array dimensions don't match other inputs")
            C_eq = C_eq.astype(dtype)
        else:
            C_eq = np.zeros((len(J), C_J.shape[1]))

        # ----- C_old -------------------------------------------------------------
        if C_old is not None:
            if not isinstance(C_old, np.ndarray):
                C_old = np.array(C_old, dtype=dtype)
            if len(C_old) != C_J.shape[1]:
                raise TypeError(
                    'C_old must have the same number of entries as C_J has columns'
                )
            C_old = C_old.astype(dtype)

        # ----- CS_init -----------------------------------------------------------
        if CS_init is not None:
            if not isinstance(CS_init, np.ndarray):
                CS_init = np.array(CS_init, dtype=dtype)
            if CS_init.ndim == 1:
                CS_init = np.tile(CS_init, (len(ST_init), 1))
            if (CS_init.shape[1] != C_J.shape[1]) or (
                CS_init.shape[0] != ST_init.shape[0] - 1
            ):
                raise TypeError("CS_init array dimensions don't match other inputs")
            CS_init = CS_init.astype(dtype)

    # ----- dt, n_substeps --------------------------------------------------------
    if dt is not None:
        dt = np.float32(dt)
    if n_substeps is not None:
        n_substeps = int(n_substeps)

    if (full_outputs is False) and (C_J is None):
        warn('No output will be generated! Are you sure you mean to do this?')

    # ---------------------------------------------------------------------------
    _verbose('Running rsas...')

    if mode in ('age', 'time'):
        warn('mode %s is deprecated, switching to RK4' % mode)
        mode = 'RK4'

    if mode == 'RK4':
        result = _solve_RK4(
            dis_rate,
            J,
            Q,
            rSAS_fun,
            ST_init=ST_init,
            dt=dt,
            n_substeps=n_substeps,
            full_outputs=full_outputs,
            CS_init=CS_init,
            C_J=C_J,
            alpha=alpha,
            k1=k1,
            C_eq=C_eq,
            C_old=C_old,
        )
    else:
        raise TypeError('Invalid solution mode.')

    return result

# get_flux
# --------------------------------------------------------------------------- #
def get_flux(i, numflux, numsol, sTt, STt, pQt, PQt, J, Q, rSAS_fun,
             mSt=None, mQt=None, mRt=None, alpha=None, k1=None, C_eq=None):
    """
    input : sTt  mSt
    output: STt  PQt  pQt  mQt  mRt
    """
    M = sTt.shape[0]

    # cumulative storage (age–ranked)
    STt[1:M + 1] = np.cumsum(sTt)
    STt[0] = 0.0

    # cumulative and incremental SAS‐based transit-time distributions
    for q in range(numflux):
        PQt[:, q] = rSAS_fun[q].cdf_i(STt, i)
    pQt[:, :] = np.diff(PQt, axis=0)

    # age-ranked solute mass fluxes
    mask = (sTt > 0.0)

    for q in range(numflux):
        for s in range(numsol):
            if q==3:
                mQt[:, q, s] = 0.0 #IGF_IN不影响溶质质量
            else:
                mQt[:, q, s] = 0.0
                mQt[mask, q, s] = (
                        (mSt[mask, s] / sTt[mask])  # 仅在有效位置做除法
                        * alpha[i, q, s]
                        * Q[i, q]
                        * pQt[mask, q]
                )

    # first-order reaction fluxes
    for s in range(numsol):
        mRt[:, s] = k1[i, s] * (C_eq[i, s] * sTt - mSt[:, s])

# --------------------------------------------------------------------------- #
# new_state
# --------------------------------------------------------------------------- #
def new_state(i, numflux, numsol, h_, sTp, sTt, pQt, J, Q,
              mSp=None, mSt=None, mQt=None, mRt=None, C_J=None):
    """
    input : sTp  mSp  mRt  pQt
    output: sTt (updated)  mSt (updated)
    """
    M = sTt.shape[0]

    # updated water storage
    sTt[:] = sTp - np.dot(Q[i, :], pQt.T) * h_ #对于IGF_IN来说 是对于不同水年龄 加入了水储量
    sTt[0] += J[i] * h_

    # updated solute storage
    for s in range(numsol):
        mSt[:, s] = mSp[:, s] + h_ * (
            mRt[:, s] - np.sum(mQt[:, :, s], axis=1)
        ) #对于IGF_IN来说  mQt[mask, 3, s]=0 因此不对mSt有影响
        mSt[0, s] += J[i] * C_J[i, s] * h_

def _solve_RK4(dis_rate,
               J,
               Q,
               rSAS_fun,
               ST_init=None,
               dt=1,
               n_substeps=1,
               full_outputs=True,
               CS_init=None,
               C_J=None,
               alpha=None,
               k1=None,
               C_eq=None,
               C_old=None):
    """rSAS model, Runge-Kutta method

    See the docstring for rsas.solve for more information
    """
    # ------------------------------------------------------------------
    # Initialisation
    # ------------------------------------------------------------------
    numflux = Q.shape[1]
    timeseries_length = len(J)
    max_age = len(ST_init) - 1
    M = max_age * n_substeps
    h = dt / float(n_substeps)

    _verbose('...initializing arrays...')
    # Optional solute bookkeeping
    if C_J is not None:
        numsol = C_J.shape[1]
    else:
        numsol = 0

    # ------------------------------------------------------------------
    # Intermediate-step arrays
    # ------------------------------------------------------------------
    ST0 = np.zeros(M + 1, dtype=np.float32)
    PQ0 = np.zeros((M + 1, numflux), dtype=np.float32)
    STt = np.zeros(M + 1, dtype=np.float32)
    PQt = np.zeros((M + 1, numflux), dtype=np.float32)

    sTp = np.zeros(M, dtype=np.float32)          # predictor water storage
    sTt = np.zeros(M, dtype=np.float32)          # current water storage
    pQ1 = np.zeros((M, numflux), dtype=np.float32)
    pQ2 = np.zeros((M, numflux), dtype=np.float32)
    pQ3 = np.zeros((M, numflux), dtype=np.float32)
    pQ4 = np.zeros((M, numflux), dtype=np.float32)
    pQn = np.zeros((M, numflux), dtype=np.float32)
    sTn = np.zeros(M, dtype=np.float32)          # storage at previous step

    # ------------------------------------------------------------------
    # Solute arrays (only if numsol > 0)
    # ------------------------------------------------------------------
    if numsol > 0:
        mQ1 = np.zeros((M, numflux, numsol), dtype=np.float32)
        mQ2 = np.zeros((M, numflux, numsol), dtype=np.float32)
        mQ3 = np.zeros((M, numflux, numsol), dtype=np.float32)
        mQ4 = np.zeros((M, numflux, numsol), dtype=np.float32)
        mR1 = np.zeros((M, numsol), dtype=np.float32)
        mR2 = np.zeros((M, numsol), dtype=np.float32)
        mR3 = np.zeros((M, numsol), dtype=np.float32)
        mR4 = np.zeros((M, numsol), dtype=np.float32)
        mQn = np.zeros((M, numflux, numsol), dtype=np.float32)
        mRn = np.zeros((M, numsol), dtype=np.float32)
        mSp = np.zeros((M, numsol), dtype=np.float32)
        mSn = np.zeros((M, numsol), dtype=np.float32)
        mSt = np.zeros((M, numsol), dtype=np.float32)
        C_Q = np.zeros((timeseries_length, numflux, numsol), dtype=np.float32)

    # ------------------------------------------------------------------
    # Arrays for full diagnostic output
    # ------------------------------------------------------------------
    if full_outputs:
        ST = np.zeros((max_age + 1, timeseries_length + 1), dtype=np.float32)
        WaterBalance = np.zeros((max_age, timeseries_length), dtype=np.float32)
        PQ = np.zeros((max_age + 1, timeseries_length + 1, numflux),
                      dtype=np.float32)

        if numsol > 0:
            MS = np.zeros((max_age + 1, timeseries_length + 1, numsol),
                          dtype=np.float32)
            MQ = np.zeros((max_age + 1, timeseries_length + 1,
                           numflux, numsol), dtype=np.float32) #怎么处理IGF_IN
            MR = np.zeros((max_age + 1, timeseries_length + 1, numsol),
                          dtype=np.float32)
            SoluteBalance = np.zeros((max_age, timeseries_length, numsol),
                                     dtype=np.float32)

    _verbose('...setting initial conditions...')

    # ------------------------------------------------------------------
    # The remainder of the RK4 time-stepping algorithm follows here...
    # ------------------------------------------------------------------
    # ------------------------------------------------------------------
    # Now we solve the governing equation
    # Set up initial and boundary conditions
    # ------------------------------------------------------------------

    # ---------- 初始条件：ST0, PQ0, sTn ----------
    if ST_init is not None:
        # ST_init : (m + 1) × 1  →  length = max_age + 1
        # 将每个年龄段再细分 n_substeps 份
        ST0[1:] = (np.cumsum(np.diff(ST_init).repeat(n_substeps))) / float(n_substeps)

        # 初始时刻各出流（Q 列）对应的累计 TTD
        for q in range(numflux):
            PQ0[:, q] = rSAS_fun[q].cdf_i(ST0, 0)

    # sTn 为每个细分年龄段的水量
    sTn[:] = np.diff(ST0)

    # ---------- 初始条件：mSn ----------
    if CS_init is not None:
        for s in range(numsol):
            # 将每个年龄段的初始浓度重复 n_substeps 次，以匹配 sTn 的分辨率
            mSn[:, s] = CS_init[:, s].repeat(n_substeps) * sTn

    # ---------- 初始化输出（t = 0）----------
    if full_outputs:
        # 水量-年龄分布
        ST[:, 0] = ST0[0:M + 1:n_substeps]
        # 累计 TTD
        PQ[:, 0, :] = PQ0[0:M + 1:n_substeps, :]
        if numsol > 0:
            # 溶质-年龄分布
            MS[:, 0, :] = np.r_[
                np.zeros((1, numsol)),
                np.cumsum(mSn, axis=0)
            ][0:M + 1:n_substeps]

    start_time = time.perf_counter()
    _verbose('...solving conservation law...')
    # ------------------------------------------------------------------
    # Primary solution loop over time t
    # ------------------------------------------------------------------
    for i in range(timeseries_length):
        # ---------------- Loop over sub-steps -------------------------
        for k in range(n_substeps):
            _debug('(i,k) = {}/{}, {}/{}, '.format(
                i, timeseries_length, k, n_substeps))

            # ---------- 重新构造 predictor 存储 sTp（以及 mSp） ----------
            sTp[1:M] = sTn[0:M - 1] #考虑随时间增加变老的过程
            sTp[0] = 0.0

            if numsol > 0:
                mSp[1:M, :] = mSn[0:M - 1, :] #考虑随时间增加变老的过程
                mSp[0, :] = 0.0

            # ---------- 四阶 Runge-Kutta 系列调用 -----------------------
            if numsol > 0:
                # k1 ：pQ1相当于k1
                get_flux(i, numflux, numsol, sTp, STt, pQ1, PQt,
                         J, Q, rSAS_fun, mSp, mQ1, mR1,
                         alpha, k1, C_eq) #pQ1 mQ1 mR1 ；不改变sTp

                # k2
                new_state(i, numflux, numsol, h / 2.0, sTp, sTt, pQ1,
                          J, Q, mSp, mSt, mQ1, mR1, C_J) #sTt mst 每次被覆盖改变
                get_flux(i, numflux, numsol, sTt, STt, pQ2, PQt,
                         J, Q, rSAS_fun, mSt, mQ2, mR2,
                         alpha, k1, C_eq) #pQ2 mQ2

                # k3
                new_state(i, numflux, numsol, h / 2.0, sTp, sTt, pQ2,
                          J, Q, mSp, mSt, mQ2, mR2, C_J)#sTt mSt
                get_flux(i, numflux, numsol, sTt, STt, pQ3, PQt,
                         J, Q, rSAS_fun, mSt, mQ3, mR3,
                         alpha, k1, C_eq) #pQ3 mQ3

                # k4
                new_state(i, numflux, numsol, h, sTp, sTt, pQ3,
                          J, Q, mSp, mSt, mQ3, mR3, C_J)#sTt mSt
                get_flux(i, numflux, numsol, sTt, STt, pQ4, PQt,
                         J, Q, rSAS_fun, mSt, mQ4, mR4,
                         alpha, k1, C_eq)

            else:
                # ---------------- 无溶质版本 ---------------------------
                get_flux(i, numflux, numsol, sTp, STt, pQ1, PQt,
                         J, Q, rSAS_fun)
                new_state(i, numflux, numsol, h / 2.0, sTp, sTt, pQ1,
                          J, Q)
                get_flux(i, numflux, numsol, sTt, STt, pQ2, PQt,
                         J, Q, rSAS_fun)
                new_state(i, numflux, numsol, h / 2.0, sTp, sTt, pQ2,
                          J, Q)
                get_flux(i, numflux, numsol, sTt, STt, pQ3, PQt,
                         J, Q, rSAS_fun)
                new_state(i, numflux, numsol, h, sTp, sTt, pQ3,
                          J, Q)
                get_flux(i, numflux, numsol, sTt, STt, pQ4, PQt,
                         J, Q, rSAS_fun)

            _debug('Finalizing\n')

            # ---------- RK4 加权平均 ----------
            pQn[:] = (pQ1 + 2 * pQ2 + 2 * pQ3 + pQ4) / 6.0
            for q in range(numflux):
                if Q[i, q] == 0.0:
                    pQn[:, q] = 0.0

            if numsol > 0:
                mQn[:] = (mQ1 + 2 * mQ2 + 2 * mQ3 + mQ4) / 6.0
                mRn[:] = (mR1 + 2 * mR2 + 2 * mR3 + mR4) / 6.0

            # ---------- 更新主状态 sTn / mSn ----------
            if numsol > 0:
                new_state(i, numflux, numsol, h, sTp, sTn, pQn,
                          J, Q, mSp, mSn, mQn, mRn, C_J) #sTn mSn
            else:
                new_state(i, numflux, numsol, h, sTp, sTn, pQn,
                          J, Q)

            # ---------- 计算本时间步平均浓度 C_Q ----------
            for s in range(numsol):
                for q in range(numflux):
                    if Q[i, q] > 0.0:
                        C_Q[i, q, s] += (
                            np.sum(mQn[:, q, s]) / Q[i, q] / float(n_substeps)
                        ) #这里+=累积的是n_substeps的C_Q
            # ----------------------------------------------------------
            # 将 pQn、mRn、mQn 累积到输出数组（第 i+1 列，代表时间步 t = i）
            # ----------------------------------------------------------
            if full_outputs:
                # ---------- 累计 TTD（PQ） ----------
                for q in range(numflux):
                    # 第 1 行（age = 0-dt）：直接累积本 sub-step 以前的所有 pQn
                    PQ[1, i + 1, q] += np.sum(pQn[:k + 1, q]) / float(n_substeps)

                    # 第 2-max_age 行：把 pQn 重新组合成 (max_age-1)×n_substeps 的整岁块
                    PQ[2:max_age + 1, i + 1, q] += (
                        np.sum(
                            np.reshape(
                                pQn[k + 1:M - (n_substeps - k - 1), q],
                                (max_age - 1, n_substeps)
                            ),
                            axis=1
                        ) / float(n_substeps)
                    )

                    # ---------- 累积 MQ ----------
                    for s in range(numsol):
                        MQ[1, i + 1, q, s] += (
                            np.sum(mQn[:k + 1, q, s], axis=0) / float(n_substeps)
                        )
                        MQ[2:max_age + 1, i + 1, q, s] += (
                            np.sum(
                                np.reshape(
                                    mQn[k + 1:M - (n_substeps - k - 1), q, s],
                                    (max_age - 1, n_substeps)
                                ),
                                axis=1
                            ) / float(n_substeps)
                        )

                # ---------- 累积 MR ----------
                for s in range(numsol):
                    MR[1, i + 1, s] += (
                        np.sum(mRn[:k + 1, s], axis=0) / float(n_substeps)
                    )
                    MR[2:max_age + 1, i + 1, s] += (
                        np.sum(
                            np.reshape(
                                mRn[k + 1:M - (n_substeps - k - 1), s],
                                (max_age - 1, n_substeps)
                            ),
                            axis=1
                        ) / float(n_substeps)
                    )

        # ------------------------------------------------------------------
        # 储存整一个 time-step (i) 结束后的综合结果
        # ------------------------------------------------------------------
        if full_outputs:
            _debug(' Storing the result')
            _debug('  Water')

            # 总水量-年龄分布
            ST[1:max_age + 1, i + 1] = np.cumsum(sTn)[n_substeps - 1:M:n_substeps]

            # 将刚才累积的增量改为累计量
            PQ[:, i + 1, :] = np.cumsum(PQ[:, i + 1, :], axis=0)

            _debug('  WaterBalance')
            WaterBalance[1:max_age, i] = (
                np.diff(ST[0:max_age, i]) -
                np.diff(ST[1:max_age + 1, i + 1]) -
                dt * np.dot(Q[i, :],
                            np.diff(PQ[1:, i + 1, :], axis=0).T)
            )
            WaterBalance[0, i] = (
                J[i] * dt -
                ST[1, i + 1] -
                dt * np.dot(Q[i, :], PQ[1, i + 1, :] - PQ[0, i + 1, :])
            )

            if numsol > 0:
                _debug('  Solutes')

                # 溶质-年龄分布
                MS[:max_age + 1, i + 1, :] = (
                    np.r_[
                        np.zeros((1, numsol)),
                        np.cumsum(mSn, axis=0)
                    ][:M + 1:n_substeps]
                )

                # 将 MR、MQ 转为累计形式
                MR[:, i + 1, :] = np.cumsum(MR[:, i + 1, :], axis=0)
                MQ[:, i + 1, :, :] = np.cumsum(MQ[:, i + 1, :, :], axis=0)

                # 出流浓度加入“未观测”旧水分量修正
                for s in range(numsol):
                    for q in range(numflux):
                        if q==0 or q==1:
                            C_Q[i, q, s] += (
                                alpha[i, q, s] * C_old[s] * dis_rate *
                                (1.0 - PQ[max_age, i + 1, q])
                            )
                        elif q==2:
                            C_Q[i, q, s] += (
                                alpha[i, q, s] * C_old[s] * (1.0-dis_rate) *
                                (1.0 - PQ[max_age, i + 1, q])
                            )
                        elif q==3:
                            C_Q[i, q, s] += 0.0


                            # ---------- 溶质守恒误差 ----------
                for s in range(numsol):
                    _debug('  SolutesBalance')
                    SoluteBalance[1:max_age, i, s] = (
                        np.diff(MS[0:max_age, i, s], axis=0) -
                        np.diff(MS[1:max_age + 1, i + 1, s], axis=0) +
                        dt * np.diff(MR[1:, i + 1, s], axis=0) -
                        dt * np.sum(
                            np.diff(MQ[1:, i + 1, :, s], axis=0),
                            axis=1
                        )
                    )
                    SoluteBalance[0, i, s] = (
                        C_J[i, s] * J[i] * dt -
                        MS[1, i + 1, s] -
                        dt * np.sum(MQ[1, i + 1, :, s] - MQ[0, i + 1, :, s]) +
                        dt * np.sum(MR[1, i + 1, s] - MR[0, i + 1, s])
                    )

            _debug(' done\n')

        # --------------------------------------------------------------
        # 进度信息
        # --------------------------------------------------------------
        if (i + 1) % 1000 == 0:
            _verbose(
                '...done ' + str(i + 1) + ' of ' + str(max_age) +
                ' in ' + str(time.perf_counter() - start_time) + ' seconds'
            )

    # ------------------------------------------------------------------
    # 打包输出
    # ------------------------------------------------------------------
    _verbose('...making output dict...')
    if numsol > 0:
        result = {'C_Q': C_Q}
    else:
        result = {}

    if full_outputs:
        if numsol > 0:
            result.update({
                'ST': ST,
                'PQ': PQ,
                'WaterBalance': WaterBalance,
                'MS': MS,
                'MQ': MQ,
                'MR': MR,
                'C_Q': C_Q,
                'SoluteBalance': SoluteBalance
            })
        else:
            result.update({
                'ST': ST,
                'PQ': PQ,
                'WaterBalance': WaterBalance
            })

    _verbose('...done.')
    return result
